create table types (
  type_id integer primary key,
  type_name text
);

create table genres (
  genre_id integer primary key,
  genre_name text
);

create table artists (
  artist_id integer primary key,
  artist_name text,
  artist_type_id integer references types (type_id),
  artist_image_url text,
  spotify_url text,
  spotify_desc text
);

create table songs (
  song_id integer primary key,
  title text,
  artist_id integer references artists (artist_id),
  genre_id integer references genres (genre_id),
  year integer,
  bpm integer,
  energy integer,
  danceability integer,
  loudness integer,
  liveness integer,
  valence integer,
  duration integer,
  acousticness integer,
  speechiness integer,
  popularity integer
);

create table playlists (
  id integer primary key generated by default as identity,
  playlist_id integer,
  song_id integer references songs (song_id)
);

alter table types enable row level security;
alter table genres enable row level security;
alter table artists enable row level security;
alter table songs enable row level security;
alter table playlists enable row level security;

create policy "Allow public read access on types" on types for select using (true);
create policy "Allow public read access on genres" on genres for select using (true);
create policy "Allow public read access on artists" on artists for select using (true);
create policy "Allow public read access on songs" on songs for select using (true);
create policy "Allow public read access on playlists" on playlists for select using (true);
