create table playlist_names (
  playlist_id integer primary key generated by default as identity,
  name text not null
);

alter table playlist_names enable row level security;

create policy "Allow public read access on playlist_names" on playlist_names for select using (true);
create policy "Allow public insert on playlist_names" on playlist_names for insert with check (true);
create policy "Allow public update on playlist_names" on playlist_names for update using (true);
create policy "Allow public delete on playlist_names" on playlist_names for delete using (true);

create policy "Allow public insert on playlists" on playlists for insert with check (true);
create policy "Allow public delete on playlists" on playlists for delete using (true);
